name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle files
        uses: actions/cache@v4.1.1


      - name: Build the Android app
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew test
