name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Setup Java JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Clean the project
        run: ./gradlew clean

      - name: Build the Android app
        run: ./gradlew build

      - name: Cache Gradle packages
        uses: actions/cache@v4.1.1
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run unit tests
        run: ./gradlew test


      - name: Build the APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: cicd-debug.apk
          path: app/build/outputs/apk/debug/cicd-debug.apk
